### ISSUE TITLE
external sql

### ISSUE THREAD

**Issue by vitaly-t** [paavohuhtala/lodgist#16]
you have some large SQL in some places: https://github.com/paavohuhtala/lodgist/blob/9b4c07ee2a44b8c29f977bc5d45356bb6ffdef2b/server/controllers/api/LodgingSearch.ts

Moving it into external files with the help of [Query Files](https://github.com/vitaly-t/pg-promise#query-files) makes for a much better code, not to mention the useful features it gives, like option `debug` that can automatically reload the SQL without restarting the application ;)

**Comment by paavohuhtala** [comment]
Thanks for reminding me of this feature! The `debug` option is extremely useful, and it saves a lot of time since I don't have to recompile and restart all the time.  :smile:

In eff65f4ac9888368d55f45d7fe5bdd912eda3b4a I've moved the huge query from LodgingSearch.ts to an external file and included it as a QueryFile. I'll look into doing the same for all of the non-trivial queries.

**Comment by vitaly-t** [comment]
You are welcome!

B.T.W. this code is prone to error: https://github.com/paavohuhtala/lodgist/blob/75e1d3459c8283fbe72d867401f266f33bee862a/server/controllers/MyReservations.ts#L13

`oneOrNone` can resolve with `null`, and you use `results` without verification ;)

**Comment by paavohuhtala** [comment]
Thanks, once again. While the code looks dangerous, `_.groupBy` evaluates to an empty object if the collection parameter is null or undefined, which the view engine handles. Handling it explicitly would be a great idea, but since the projected lifetime of this project is ~two more weeks and the deadlines are somewhat tight, code style issues don't have a high priority.

**Comment by vitaly-t** [comment]
I was saying that `results.reservations` will throw an error when `results` is `null`, which is outside of whatever `_.groupBy` does ;)

**Comment by paavohuhtala** [comment]
Oh right, I completely missed that. For some reason I misremembered that `null.x` evaluates to `undefined`, which in retrospect doesn't make sense.

Luckily TypeScript 2 will introduce [non-nullable types and strict null checking](https://github.com/Microsoft/TypeScript/pull/7140), which will help avoiding problems like this in the future.
